const { test } = require('node:test')
const assert = require('node:assert/strict')
const { EditSession, MAX_HISTORY_CHANGES, MAX_HISTORY_STEPS } = require('../utils/editor')
const { fitView, zoomView, cellAt, visibleCells, clampView } = require('../utils/editor-view')
const { buildXlsxBuffer } = require('../utils/exporter')
const palette = [
  { colorIndex: 1, beadCode: 'H7', code: '#000000', count: 1 },
  { colorIndex: 2, beadCode: 'H2', code: '#FFFFFF', count: 1 },
  { colorIndex: 3, beadCode: 'C22', code: '#67B4BE', count: 1 }
]
const planOf = matrix => ({ matrix, detail: palette, total: matrix.flat().filter(Boolean).length,
  gridWidth: matrix[0].length, gridHeight: matrix.length, trimmedBeads: 10, paletteVersion: '221' })
const edit = (session, callback) => { session.begin(); callback(); return session.commit() }

test('draft changes are isolated; crossing strokes form one reversible history item', () => {
  const plan = planOf(Array.from({ length: 5 }, () => Array(8).fill(1)))
  const original = JSON.stringify(plan)
  const session = new EditSession(plan)
  edit(session, () => {
    session.line({ x: 0, y: 0 }, { x: 7, y: 0 }, 3)
    session.line({ x: 7, y: 0 }, { x: 7, y: 4 }, 3)
    session.line({ x: 7, y: 4 }, { x: 7, y: 0 }, 2)
  })
  assert.equal(session.undoStack.length, 1)
  assert.equal(session.historyChanges, 12)
  assert.equal(session.dirtyCount, 12)
  assert.equal(JSON.stringify(plan), original)
  session.undo()
  assert.ok(session.pixels.every(value => value === 1))
  assert.equal(session.dirtyCount, 0)
  session.redo()
  assert.equal(session.pixels[39], 2)
  assert.equal(session.dirtyCount, 12)
  session.begin(); session.write(1, 2); session.cancel()
  assert.equal(session.pixels[1], 3)
  assert.equal(session.undoStack.length, 1)
})

test('fill follows four neighbors, while global replacement reaches disconnected regions', () => {
  const session = new EditSession(planOf([[1, 1, 2, 1], [2, 1, 2, 1], [1, 2, 1, 1]]))
  edit(session, () => session.fill(0, 3))
  assert.deepEqual(Array.from(session.pixels), [3, 3, 2, 1, 2, 3, 2, 1, 1, 2, 1, 1])
  edit(session, () => session.fill(3, 2, true))
  assert.ok(!session.pixels.includes(1))
  session.undo()
  assert.equal(session.pixels[8], 1)
  session.undo()
  assert.deepEqual(Array.from(session.pixels), session.plan.matrix.flat())
})

test('eraser uses zero; saved statistics and sparse Excel distinguish white from empty', () => {
  const plan = planOf([[1, 2, 3], [3, 2, 1]])
  const session = new EditSession(plan)
  edit(session, () => { session.write(0, 0); session.write(2, 2) })
  const saved = session.save()
  assert.equal(saved.total, 5)
  assert.equal(saved.emptyCells, 1)
  assert.equal(saved.trimmedBeads, 10)
  assert.deepEqual(saved.matrix, [[0, 2, 2], [3, 2, 1]])
  assert.deepEqual(saved.detail.map(c => [c.colorIndex, c.count]), [[2, 3], [1, 1], [3, 1]])
  assert.deepEqual(saved.cellsByColor[1], [{ row: 1, col: 2 }, { row: 1, col: 3 }, { row: 2, col: 2 }])
  assert.equal(Object.values(saved.cellsByColor).flat().length, 5)
  assert.equal(saved.gridWidth, 3)
  assert.equal(saved.gridHeight, 2)
  const data = Buffer.from(buildXlsxBuffer({ plan: saved })).toString('utf8')
  const sheets = data.match(/<worksheet\b[\s\S]*?<\/worksheet>/g)
  for (const sheet of sheets.slice(0, 2)) {
    assert.match(sheet, /dimension ref="A1:C2"/)
    assert.doesNotMatch(sheet, /<c r="A1"/)
    assert.match(sheet, /<c r="B1" s="\d+"/)
    assert.equal((sheet.match(/<c /g) || []).length, 5)
  }
  assert.match(sheets[1], /<c r="B1"[^>]*><is><t>H2<\/t>/)
  assert.equal(plan.matrix[0][0], 1)
  saved.matrix[0][1] = 0
  assert.equal(session.pixels[1], 2, 'saved matrix is detached from draft')
})

test('all-empty cannot save; palette remains available; no-op and redo branching stay correct', () => {
  const session = new EditSession(planOf([[1, 2]]))
  edit(session, () => { session.write(0, 0); session.write(1, 0) })
  assert.throws(() => session.save(), /EMPTY_EDIT_PLAN/)
  assert.equal(session.palette.length, 3)
  edit(session, () => session.write(1, 2))
  assert.equal(session.save().total, 1)
  session.undo()
  assert.equal(session.redoStack.length, 1)
  assert.equal(edit(session, () => session.write(0, 0)), false)
  assert.equal(session.redoStack.length, 1)
  edit(session, () => session.write(0, 3))
  assert.equal(session.redoStack.length, 0)
  assert.equal(session.historyChanges, 3)
  session.begin()
  assert.throws(() => session.write(1, 99), /INVALID_EDIT_COLOR/)
  session.cancel()
})

test('small history caps at 20 strokes while undo/redo share the change budget', () => {
  const session = new EditSession(planOf([Array(30).fill(1)]))
  for (let i = 0; i < 30; i++) edit(session, () => session.write(i, 3))
  assert.equal(session.undoStack.length, MAX_HISTORY_STEPS)
  assert.equal(session.historyChanges, 20)
  for (let i = 0; i < 20; i++) session.undo()
  assert.equal(session.dirtyCount, 10)
  assert.equal(session.historyChanges, 20)
  assert.equal(session.redoStack.length, 20)
  edit(session, () => session.write(29, 2))
  assert.equal(session.historyChanges, 1)
})

test('million-cell fill, erase and undo stay within the two-million-change budget', () => {
  const session = new EditSession(planOf(Array.from({ length: 1000 }, () => Array(1000).fill(1))))
  const started = performance.now()
  edit(session, () => session.fill(0, 3))
  assert.ok(session.pixels.every(v => v === 3))
  edit(session, () => session.fill(0, 2, true))
  assert.equal(session.historyChanges, MAX_HISTORY_CHANGES)
  edit(session, () => session.fill(0, 0))
  assert.equal(session.historyChanges, MAX_HISTORY_CHANGES)
  assert.equal(session.undoStack.length, 2)
  session.undo(); session.undo()
  assert.ok(session.pixels.every(v => v === 3))
  assert.equal(session.undo(), false)
  session.redo()
  assert.ok(session.pixels.every(v => v === 2))
  console.log(`[editor-benchmark] million-cell fill/replace/erase + undo/redo: ${Math.round(performance.now() - started)} ms`)
})

test('rectangular hit testing, anchored zoom and panning respect grid edges', () => {
  const view = fitView(200, 200, 20, 10)
  assert.equal(cellAt(view, { x: 0, y: 49 }), null)
  assert.deepEqual(cellAt(view, { x: 0, y: 50 }), { x: 0, y: 0 })
  assert.deepEqual(cellAt(view, { x: 199.99, y: 149.99 }), { x: 19, y: 9 })
  assert.equal(cellAt(view, { x: 200, y: 150 }), null)
  const point = { x: 100, y: 100 }, before = cellAt(view, point)
  zoomView(view, 2, point)
  assert.deepEqual(cellAt(view, point), before)
  view.left = -9999; view.top = 9999; clampView(view)
  assert.equal(view.left, -200)
  assert.equal(view.top, 0)
  const large = fitView(320, 400, 1000, 1000)
  zoomView(large, 20 / large.cell, { x: 160, y: 200 })
  const bounds = visibleCells(large)
  assert.ok((bounds.x1 - bounds.x0) * (bounds.y1 - bounds.y0) <= 400)
})
